# Generated by Django 3.2.3 on 2023-03-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=18)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
